# 2GB ram minimum for kubernetes
default_os_image: rancheros-1560459796

ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

docker_lib: docker-ce=17.03.2~ce-0~ubuntu-xenial
kubernetes_version: 1.11.3
kubernetes_apt_version: 1.11.3-00
cni_apt_version: 0.6.0-00
kubeadm_extra_args: "--pod-network-cidr=10.244.0.0/16 --kubernetes-version {{ kubernetes_version }} --apiserver-cert-extra-sans '{{ ansible_host  }}'"
flannel_version: c5d10c8
kube_flannel_url: "https://raw.githubusercontent.com/coreos/flannel/{{ flannel_version }}/Documentation/kube-flannel.yml"
main_security_groups:
  - group: "manage{{ suffix }}" 
    port: 22 
    remote_ip_prefix: "0.0.0.0/0"


security_groups: "{{ main_security_groups + host_security_groups }}"

