
security_groups:
  - {group: "swarm-sg{{ suffix }}", port: 22, remote_ip_prefix: "{{ ssh_remote_cidr }}"}
  - {group: "swarm-sg{{ suffix }}", port: 5000, remote_ip_prefix: "{{ ssh_remote_cidr }}"}
  - {group: "swarm-sg{{ suffix }}", port: 5001, remote_ip_prefix: "{{ ssh_remote_cidr }}"}
  - {group: "swarm-sg{{ suffix }}", port: 8080, remote_ip_prefix: "{{ ssh_remote_cidr }}"}
