---


- name: Provision manager in catalyst cloud
  hosts: "{{ lookup('env', 'PREFIX') }}:&dashboard"
  gather_facts: false
  serial: 1
  tasks:
    - block:
        - import_tasks: tasks/catalyst-cloud.yml
      delegate_to: localhost


- name: Start the rancher server
  hosts: "{{ lookup('env', 'PREFIX') }}:&dashboard"
  gather_facts: false
  tasks:

    - name: Start running rancher server
      raw: docker run -d --restart=unless-stopped --name rancher-dash -p 80:80 -p 443:443 rancher/rancher:{{ rancher_image_version }} > rancher_image_id
      args:
        creates: rancher_image_id
