---

- name: Fetch subnet info for tenant
  hosts: "{{ lookup('env', 'PREFIX') }}:&bastion"
  gather_facts: false
  tasks:
    - block:
      - name: Fetch subnet for kubernetes cluster
        os_subnets_info:
          cloud: "{{ cloud_name }}"
        register: subnet_result
      delegate_to: localhost
    
    - name: Set the network id
      set_fact:
        network_id: "{{ subnet_result.openstack_subnets | selectattr('name', 'match', '^' + prefix + '.*') | map(attribute='network_id') | first }}"

- name: Provision manager in catalyst cloud
  hosts: "{{ lookup('env', 'PREFIX') }}:&dashboard"
  gather_facts: false
  tasks:
    - block:
      - import_tasks: tasks/catalyst-cloud-auth.yml
      - import_tasks: tasks/catalyst-cloud-network.yml
      delegate_to: localhost


- name: Provision manager in catalyst cloud
  hosts: "{{ lookup('env', 'PREFIX') }}"
  gather_facts: false
  tasks:
    - block:
      - import_tasks: tasks/catalyst-cloud-auth.yml
      - import_tasks: tasks/catalyst-cloud-host.yml
      delegate_to: localhost



- name: Start the rancher server
  hosts: "{{ lookup('env', 'PREFIX') }}:&dashboard"
  gather_facts: false
  tasks:

    - name: Start running rancher server
      raw: docker run -d --restart=unless-stopped --name rancher-dash -p 80:80 -p 443:443 rancher/rancher:{{ rancher_image_version }} > rancher_image_id
      args:
        creates: rancher_image_id

    - name: Output command to open rancher
      debug:
        msg: "firefox https://{{ ansible_host }}"

- name: Output bastion access instructions
  hosts: "{{ lookup('env', 'PREFIX') }}:&bastion"
  gather_facts: false
  tasks:
    - name: Retrieve master machine private ip
      command: openstack coe cluster show --os-cloud {{ cloud_name }} {{ prefix }} -c api_address -f value
      register: master_private_ip_result
      delegate_to: localhost

    - name: Output SSH tunnel command
      debug:
        msg: "ssh -f -L 6443:{{ master_private_ip }}:6443 ubuntu@{{ ansible_host }} -N"

