---
- name: Preflight to set up machine specific variables
  hosts: cluster
  gather_facts: false
  tasks:
    - debug:
        var: prefix | mandatory


- name: Provision manager in catalyst cloud
  hosts: manager
  gather_facts: false
  serial: 1
  tasks:
    - block:
        - import_tasks: tasks/catalyst-cloud.yml
      delegate_to: localhost

- name: Kick off docker management
  hosts: manager
  gather_facts: false
  become: true
  tasks:
    - name: Kick off rancheros server
      raw:  docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher
      ignore_errors: true

