---

- name: Fetch subnet info for tenant
  hosts: "{{ lookup('env', 'PREFIX') }}:&bastion"
  gather_facts: false
  tasks:
    - block:
      - name: Fetch subnet for kubernetes cluster
        os_subnets_info:
          cloud: "{{ cloud_name }}"
        register: subnet_result
      delegate_to: localhost
    
    - name: Set the network id
      set_fact:
        network_id: "{{ subnet_result.openstack_subnets | selectattr('name', 'match', '^travis-training-k8s.*') | map(attribute='network_id') | first }}"

- name: Provision manager in catalyst cloud
  hosts: "{{ lookup('env', 'PREFIX') }}:&dashboard"
  gather_facts: false
  serial: 1
  tasks:
    - block:
      - import_tasks: tasks/catalyst-cloud-auth.yml
      - import_tasks: tasks/catalyst-cloud-network.yml
      delegate_to: localhost


- name: Provision manager in catalyst cloud
  hosts: "{{ lookup('env', 'PREFIX') }}"
  gather_facts: false
  serial: 1
  tasks:
    - block:
      - import_tasks: tasks/catalyst-cloud-auth.yml
      - import_tasks: tasks/catalyst-cloud-host.yml
      delegate_to: localhost


- name: Start the rancher server
  hosts: "{{ lookup('env', 'PREFIX') }}:&dashboard"
  gather_facts: false
  tasks:

    - name: Start running rancher server
      raw: docker run -d --restart=unless-stopped --name rancher-dash -p 80:80 -p 443:443 rancher/rancher:{{ rancher_image_version }} > rancher_image_id
      args:
        creates: rancher_image_id
