---

- name: Teardown Catalyst Cloud hosts
  hosts: "{{ lookup('env', 'PREFIX') }}:&dashboard"
  gather_facts: false
  tasks:
    - block:
        - block:
            - name: Connect to Catalyst Cloud
              os_auth:
                cloud: "{{ cloud_name }}"

            - name: Remove host name from known_hosts
              known_hosts:
                name: "{{ inventory_hostname }}"
                state: absent

            - name: Remove host ip from known_hosts
              known_hosts:
                name: "{{ ansible_host }}"
                state: absent


            - name: Remove servers
              os_server:
                cloud: "{{ cloud_name }}"
                name: "{{ inventory_hostname }}"
                state: absent
          tags: 
            - node_only

        - name: Remove ports
          os_port:
            cloud: "{{ cloud_name }}"
            name: "{{ inventory_hostname }}"
            state: absent

        - name: Remove cluster keypair
          os_keypair: 
            cloud: "{{ cloud_name }}"
            state: absent
            name: "{{ keypair_name }}"
      delegate_to: localhost

- name: Teardown networks and security groups
  hosts: "{{ lookup('env', 'PREFIX') }}:&dashboard"
  gather_facts: false
  run_once: true
  tasks:
    - block:
        - name: Remove cluster router
          os_router:
            cloud: "{{ cloud_name }}"
            state: absent
            name: "{{ router_name }}"

        - name: Remove cluster network
          os_network:
            cloud: "{{ cloud_name }}"
            state: absent
            name: "{{ network_name }}"

        - name: Remove security group
          os_security_group:
            cloud: "{{ cloud_name }}"
            name: "{{ item }}"
            state: absent
          with_items: "{{ security_group_names }}"
      delegate_to: localhost

