
- src: https://github.com/heytrav/ansible-docker.git
  scm: git
  name: docker
  version: master

- src: https://github.com/heytrav/ansible-setup-openstack.git
  scm: git
  name: openstack-cloud
  version: master

- src: https://github.com/heytrav/ansible-docker-compose.git
  scm: git
  name: docker-compose
  version: master

- src: https://github.com/heytrav/ansible-minikube.git
  scm: git
  name: trainingpc-minikube
  version: master
