---

- name: Create network
  os_network:
    name: "{{ network_name }}"
    state: present
    cloud: "{{ cloud_name }}"
  register: network_result

- name: Create subnet
  os_subnet:
    name: "{{ subnet_name }}"
    network_name: "{{ network_name }}"
    state: present
    cidr: "{{ subnet_cidr }}"
    allocation_pool_start: "{{ subnet_dhcp_start }}"
    allocation_pool_end: "{{ subnet_dhcp_end }}"
    ip_version: 4
    dns_nameservers: "{{ default_nameservers }}"
    cloud: "{{ cloud_name }}"


- name: Create router
  os_router:
    cloud: "{{ cloud_name }}"
    state: present
    name: "{{ router_name }}"
    network: "{{ public_net_name }}"
    interfaces:
      - "{{ subnet_name }}"

