---
- name: Connect to Catalyst Cloud
  os_auth:
    cloud: "{{ cloud_name }}"

- name: Create keypair
  os_keypair:
    name: "{{ keypair_name }}"
    public_key: "{{ ssh_public_key }}"
    cloud: "{{ cloud_name }}"

- name: Create Network
  os_network:
    name: "{{ network_name }}"
    state: present
    cloud: "{{ cloud_name }}"

- name: Create subnet
  os_subnet:
    name: "{{ subnet_name }}"
    network_name: "{{ network_name }}"
    state: present
    cidr: "{{ subnet_cidr }}"
    allocation_pool_start: "{{ subnet_dhcp_start }}"
    allocation_pool_end: "{{ subnet_dhcp_end }}"
    ip_version: 4
    dns_nameservers: "{{ default_nameservers }}"
    cloud: "{{ cloud_name }}"


- name: Create router
  os_router:
    cloud: "{{ cloud_name }}"
    state: present
    name: "{{ router_name }}"
    network: "{{ public_net_name }}"
    interfaces:
      - "{{ subnet_name }}"

- name: Create security groups
  os_security_group:
    cloud: "{{ cloud_name }}"
    state: present
    name: "{{ item }}"
  with_items: "{{ security_group_names }}"

- name: Add rules for security group
  os_security_group_rule:
    cloud: "{{ cloud_name }}"
    state: present
    security_group: "{{ item.group }}"
    protocol: "{{ item.proto | default('tcp') }}"
    port_range_min: "{{ omit if item.port == 'any' else item.port }}"
    port_range_max: "{{ omit if item.port == 'any' else item.port_end | default(item.port) }}"
    remote_ip_prefix: "{{ item.remote_ip_prefix | default(omit) }}"
    remote_group: "{{ item.remote_group | default(omit) }}"
  with_items: "{{ security_groups }}"


- name: Create cluster instances
  os_server:
    cloud: "{{ cloud_name }}"
    state: present
    name: "{{ inventory_hostname }}"
    image: "{{ default_os_image }}"
    key_name: "{{ keypair_name  }}"
    flavor: "{{ default_flavor }}"
    config_drive: yes
    nics:
      - net-name: "{{ network_name }}"
    security_groups: "default,{{ security_group_names | unique | join(',')}}"
    meta: 
      inventory_hostname: "{{ inventory_hostname }}"
      groups: "{{ prefix }},{{ group_names | join(',') }}"
    userdata: "{{ lookup('template', 'templates/cloud-config.j2') }}"

- name: Assign floating ips
  os_floating_ip:
    cloud: "{{ cloud_name }}"
    state: present
    reuse: yes
    wait: true
    server: "{{ inventory_hostname }}"
  register: floating_ip_info

- name: Append floating ip to host info
  add_host:
    name: "{{ inventory_hostname }}"
    ansible_host: "{{ floating_ip_info.floating_ip.floating_ip_address }}"
    ansible_user: "{{ hostvars[inventory_hostname].ansible_user }}"
    fixed_ip: "{{ floating_ip_info.floating_ip.fixed_ip_address }}"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    ansible_python_interpreter: /usr/bin/python

- wait_for:
    host: "{{ hostvars[inventory_hostname].ansible_host }}"
    port: 22
